=== yangyang2022/DemoProject/WebService01/src/main/dtd/classroom.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT classroom (classname,grade,students)>
<!ATTLIST classroom id ID #REQUIRED>
<!ELEMENT classname (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT students (student+)>
<!ELEMENT student (id,name,age)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== yangyang2022/DemoProject/WebService01/src/main/dtd/classroom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classroom SYSTEM "classroom.dtd">
 <classroom id="c1">
    <classname>计算机</classname>
    <grade>2011</grade>
    <students>
        <student>
            <id>1</id>
            <name>zhangsan</name>
            <age>12</age>
        </student>
        <student>
            <id>2</id>
            <name>lisi</name>
            <age>12</age>
        </student>
    </students>
</classroom>
